var players = [
    { id: 1, name: "יואב כרמל", group: "בית תורמוס", seed: "Yoav" },
    { id: 2, name: "נמרוד מקובר", group: "בית תורמוס", seed: "Nimrod" },
    { id: 3, name: "גיל גורני", group: "בית תורמוס", seed: "Gil" },
    { id: 4, name: "עמית שבתאי לוי", group: "בית תורמוס", seed: "Amit" },
    { id: 5, name: "ניב סמיה", group: "בית תורמוס", seed: "Niv" },
    { id: 6, name: "רז סלמה", group: "בית סינג'יל", seed: "Raz" },
    { id: 7, name: "יובל פישל", group: "בית סינג'יל", seed: "Yuval" },
    { id: 8, name: "יניב אוזלאי", group: "בית סינג'יל", seed: "Yaniv" },
    { id: 9, name: "יאיר", group: "בית סינג'יל", seed: "Yair" },
    { id: 10, name: "חן בנימין", group: "בית סינג'יל", seed: "Chen" },
    { id: 11, name: "עומר גליקסמן", group: "בית שילה", seed: "Omer" },
    { id: 12, name: "ניצן בן צבי", group: "בית שילה", seed: "Nitzan" },
    { id: 13, name: "כפיר פורטר", group: "בית שילה", seed: "Kfir" },
    { id: 14, name: "סהר מחווי", group: "בית שילה", seed: "Sahar" },
    { id: 15, name: "גל שמואלי", group: "בית שילה", seed: "Gal" },
    { id: 16, name: "יואש רון", group: "בית עלי", seed: "Yoash" },
    { id: 17, name: "איתי דדון", group: "בית עלי", seed: "Itai" },
    { id: 18, name: "רותם", group: "בית עלי", seed: "Rotem" },
    { id: 19, name: "אילאן בביקוב", group: "בית עלי", seed: "Ilan" },
    { id: 20, name: "אביב לובטון", group: "בית עלי", seed: "Aviv" },
    { id: 21, name: "אופיר בר", group: "בית לובאן", seed: "Ofir" },
    { id: 22, name: "זיו מימון", group: "בית לובאן", seed: "Ziv" },
    { id: 23, name: "דביר שאול", group: "בית לובאן", seed: "Shaul" },
    { id: 24, name: "איתי רזניק", group: "בית לובאן", seed: "Reznik" },
    { id: 25, name: "ליאור מנטקה", group: "בית לובאן", seed: "Lior" },
    { id: 26, name: "אלון מזרחי", group: "בית הדורבן", seed: "Alon" },
    { id: 27, name: "שון", group: "בית הדורבן", seed: "Sean" },
    { id: 28, name: "גיא שורר", group: "בית הדורבן", seed: "Guy" },
    { id: 29, name: "עידן", group: "בית הדורבן", seed: "Idan" },
    { id: 30, name: "עומר תלמי", group: "בית הדורבן", seed: "Talmi" },
    { id: 31, name: "אורי צ'צ'קס", group: "בית ששון", seed: "Ori" },
    { id: 32, name: "הדר גרין", group: "בית ששון", seed: "Hadar" },
    { id: 33, name: "אפיק שרייבר", group: "בית ששון", seed: "Afik" },
    { id: 34, name: "שמעון רוז", group: "בית ששון", seed: "Shimon" },
    { id: 35, name: "אוראל זר", group: "בית ששון", seed: "Orel" }
];

var groupNames = ["בית תורמוס", "בית סינג'יל", "בית שילה", "בית עלי", "בית לובאן", "בית הדורבן", "בית ששון"];
