var players = [
    { id: 1, name: "יואב כרמל", group: "A", seed: "Yoav" },
    { id: 2, name: "נמרוד מקובר", group: "A", seed: "Nimrod" },
    { id: 3, name: "גיל גורני", group: "A", seed: "Gil" },
    { id: 4, name: "עמית שבתאי לוי", group: "A", seed: "Amit" },
    { id: 5, name: "ניב סמיה", group: "A", seed: "Niv" },
    { id: 6, name: "רז סלמה", group: "B", seed: "Raz" },
    { id: 7, name: "יובל פישל", group: "B", seed: "Yuval" },
    { id: 8, name: "יניב אוזלאי", group: "B", seed: "Yaniv" },
    { id: 9, name: "יאיר", group: "B", seed: "Yair" },
    { id: 10, name: "חן בנימין", group: "B", seed: "Chen" },
    { id: 11, name: "עומר גליקסמן", group: "C", seed: "Omer" },
    { id: 12, name: "ניצן בן צבי", group: "C", seed: "Nitzan" },
    { id: 13, name: "כפיר פורטר", group: "C", seed: "Kfir" },
    { id: 14, name: "אוהד אגם", group: "C", seed: "Ohad" },
    { id: 15, name: "סהר מחווי", group: "C", seed: "Sahar" },
    { id: 16, name: "גל שמואלי", group: "D", seed: "Gal" },
    { id: 17, name: "יואש רון", group: "D", seed: "Yoash" },
    { id: 18, name: "איתי דדון", group: "D", seed: "Itai" },
    { id: 19, name: "רותם", group: "D", seed: "Rotem" },
    { id: 20, name: "אילאן בביקוב", group: "E", seed: "Ilan" },
    { id: 21, name: "אביב לובטון", group: "E", seed: "Aviv" },
    { id: 22, name: "אופיר בר", group: "E", seed: "Ofir" },
    { id: 23, name: "זיו מימון", group: "E", seed: "Ziv" },
    { id: 24, name: "דביר שאול", group: "F", seed: "Shaul" },
    { id: 25, name: "איתי רזניק", group: "F", seed: "Reznik" },
    { id: 26, name: "ליאור מנטקה", group: "F", seed: "Lior" },
    { id: 27, name: "אלון מזרחי", group: "F", seed: "Alon" },
    { id: 28, name: "שון", group: "G", seed: "Sean" },
    { id: 29, name: "גיא שורר", group: "G", seed: "Guy" },
    { id: 30, name: "עידן", group: "G", seed: "Idan" },
    { id: 31, name: "עומר תלמי", group: "G", seed: "Talmi" },
    { id: 32, name: "אורי צ'צ'קס", group: "H", seed: "Ori" },
    { id: 33, name: "הדר גרין", group: "H", seed: "Hadar" },
    { id: 34, name: "אפיק שרייבר", group: "H", seed: "Afik" },
    { id: 35, name: "שמעון רוז", group: "H", seed: "Shimon" }
];

var groupNames = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
