var players = [
    { id: 1, name: "אהבת השם מקובר", group: "בית לובאן", seed: "Mekover" },
    { id: 2, name: "איליאן בביקוב", group: "בית לובאן", seed: "Bebikov" },
    { id: 3, name: "יובל פישל", group: "בית לובאן", seed: "Fishel" },
    { id: 4, name: "ניב סמיה", group: "בית לובאן", seed: "Samia" },
    { id: 5, name: "שון אשכנזי", group: "בית לובאן", seed: "Ashkenazi" },
    { id: 6, name: "רז סלמה", group: "בית עלי", seed: "Salame" },
    { id: 7, name: "יואש רון", group: "בית עלי", seed: "Ron" },
    { id: 8, name: "אלון מזרחי", group: "בית עלי", seed: "Mizrahi" },
    { id: 9, name: "אפיק שרייבר", group: "בית עלי", seed: "Schreiber" },
    { id: 10, name: "גל שמואלי", group: "בית עלי", seed: "Shmueli" },
    { id: 11, name: "יואב כרמל", group: "בית השב\"ח", seed: "Carmel" },
    { id: 12, name: "סהר מחווי", group: "בית השב\"ח", seed: "Mahvi" },
    { id: 13, name: "ניצן בן צבי", group: "בית השב\"ח", seed: "BenZvi" },
    { id: 14, name: "עומר תלמי", group: "בית השב\"ח", seed: "Talmi" },
    { id: 15, name: "אורי צ'צ'קס", group: "בית השב\"ח", seed: "Chechkes" },
    { id: 16, name: "גיל גורני", group: "בית תורמוס", seed: "Gorni" },
    { id: 17, name: "יניב אזולאי", group: "בית תורמוס", seed: "Azulai" },
    { id: 18, name: "איתי רזניק", group: "בית תורמוס", seed: "Reznik" },
    { id: 19, name: "הדר גרין", group: "בית תורמוס", seed: "Green" },
    { id: 20, name: "מור ברזילי", group: "בית תורמוס", seed: "Barzilai" },
    { id: 21, name: "אביב לובטון", group: "בית הלוזר", seed: "Luvaton" },
    { id: 22, name: "עמית שבתאי", group: "בית הלוזר", seed: "Shabtai" },
    { id: 23, name: "רותם צור", group: "בית הלוזר", seed: "Tzur" },
    { id: 24, name: "גיא שורר", group: "בית הלוזר", seed: "Shorer" },
    { id: 25, name: "זיו מימון", group: "בית הלוזר", seed: "Maimon" },
    { id: 26, name: "כפיר פורטר", group: "בית הדורבן", seed: "Porter" },
    { id: 27, name: "אופיר בר", group: "בית הדורבן", seed: "Bar" },
    { id: 28, name: "דביר שאול", group: "בית הדורבן", seed: "Shaul" },
    { id: 29, name: "איתי דדון", group: "בית הדורבן", seed: "Dadon" },
    { id: 30, name: "שמעון רוז", group: "בית הדורבן", seed: "Rose" },
    { id: 31, name: "אוראל זר", group: "בית ששון/ששי'לה", seed: "Orel" },
    { id: 32, name: "עומר גליקסמן", group: "בית ששון/ששי'לה", seed: "Glicksman" },
    { id: 33, name: "עידן אוסטרובסקי", group: "בית ששון/ששי'לה", seed: "Ostrovsky" },
    { id: 34, name: "ליאור אביב", group: "בית ששון/ששי'לה", seed: "Aviv" }
];

var groupNames = ["בית לובאן", "בית עלי", "בית השב\"ח", "בית תורמוס", "בית הלוזר", "בית הדורבן", "בית ששון/ששי'לה"];
